# Generated by Django 4.1 on 2022-09-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blogging",
            "0003_alter_category_options_remove_category_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
