# Generated by Django 4.1 on 2022-09-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0004_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="blogging.post"
            ),
        ),
    ]
